apiVersion: apps/v1 # Use the stable "apps/v1" API group for Deployments
kind: Deployment # This resource is a Deployment (manages pods + rolling updates)
metadata:
  name: auth-depl # Name of this Deployment object (used in kubectl commands)
spec:
  replicas: 1 # Keep exactly 1 pod instance running at all times
  selector:
    matchLabels:
      app: auth # This Deployment manages any pod labeled "app: auth"
  template: # Blueprint used to create each pod
    metadata:
      labels:
        app: auth # Label applied to pods so the selector above can find them
    spec:
      containers:
        - name: auth # Name of the container inside the pod (for logs/exec)
          image: us.gcr.io/tickets-503310/auth # Docker image to pull & run (from Google Container Registry, no tag = defaults to :latest)

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
